### ISSUE TITLE
Take a picture of a bill

### ISSUE THREAD

**Issue by jjxxs** [mobileappdevhm20/team-project-team_6#1]
A user should be able to take a picture of a bill that he received while shopping. After taking the picture he should be shown the picture so that he can decide if the picture is good enough (e.g. good lightning, the whole bill can be seen of the picture). He should also be able to crop the picture to the relevant parts.

- [x] The user can take a picture of a bill.
- [x] After taking the picture, the picture is shown to the user.
- [x] The user can crop the picture to only show relevant information.
- [x] The user can decide if the picture is good enough and should be parsed, retry to take a better picture or cancel the process.

// Notes:
Maybe this library will be helpful
https://github.com/Yalantis/uCrop

**Comment by salman2893** [comment]
I used the [Android-ImageCropper](https://github.com/ArthurHub/Android-Image-Cropper) to implement the feature.
- The user can take a picture using the camera or by choosing one from the galery
- The user can crop the image
- The image is then displayed to the user
- The user can either choose to scan the image or to take a new one
