### ISSUE TITLE
Create views according to figma-design

### ISSUE THREAD

**Issue by salman2893** [mobileappdevhm20/team-project-team_6#11]
Create and design the app views according to the [figma prototype design](https://www.figma.com/file/U0r2xmu9Fyja9gI72Z8CTx/EasyBill).

- [x] Archive View
- [x] Scan View
- [x] Statistics View
- [x] Filter View

**Comment by ReneNeu** [comment]
Most views are self-explanatory. For example, archiv is of course the archive and archiv_list_view_item is the layout for the listview. Where it is just a little confusing in the statistics, we will go into more detail here to make sure this is recorded:

**statistic** represents the overview in general:
![image](https://user-images.githubusercontent.com/43846116/83347899-7aa6ea00-a328-11ea-8454-b27a8260f8f9.png)


But to be able to display a month with prices and desired categories here, we need a listview again. For this we have **statistic_listview_month_overview**.
The month, the price and a listview with the categories of the month are always displayed here.

The listview here in **statistic_listview_month_overview** is filled with the layout **statstic_list_view_item**. Which always has a placeholder for the category and the total price.

If you click on a category, the fileview will be loaded which is in **statistic_detailed_view**.
Here you can see the selected month and the invoices in a listview below.

**Comment by ReneNeu** [comment]
All views are created and merged in the develop branch

**Comment by ReneNeu** [comment]
Update Filter design and add images to the buttons.
