### ISSUE TITLE
Display view based on aspect ratio/resolution

### ISSUE THREAD

**Issue by WagnerThomas** [mobileappdevhm20/team-project-team_6#36]
Views need to be displayed based on a phone aspect ratio and resolution. 
At the moment with different ratios content would be displayed differently.

- [x] fix design to look good at every ratio

**Comment by ReneNeu** [comment]
This is done by the constrain layout, some constraints have been changed and the sizes of the text fields have been replaced with wrap content instead of fixed sizes
