### ISSUE TITLE
Apply filters to the archived bills

### ISSUE THREAD

**Issue by jjxxs** [mobileappdevhm20/team-project-team_6#5]
There should be the option to filter all saved bills (e.g. the archive) by certain values (e.g. time, sum, product).

- [x] There is a filter mask that the user can use to input filter-criteria.
- [x] Saved bills can be filtered by various criteria.
- [x] There is a view that shows the result of the filtered result set.

**Comment by WagnerThomas** [comment]
Filtering based on category will not be implemented yet.

There will be an option in the view but it'll do nothing because its not quite possible to automatically store bills with categories.

Still some view revamp to do but the logic behind can be implemented easily

**Comment by WagnerThomas** [comment]
Filtering the bills is implemented via the viewmodelclass
Now able to filter by price  and by year.
