### ISSUE TITLE
Statistics crashing the app 

### ISSUE THREAD

**Issue by WagnerThomas** [mobileappdevhm20/team-project-team_6#51]
If no bills stored in the app, it will crash if you go to the statsistics tab.

```java.time.DateTimeException: Instant exceeds minimum or maximum instant```

**Comment by jjxxs** [comment]
Fixed in https://github.com/mobileappdevhm20/team-project-team_6/commit/2bbdd1ee18453ae6e59b7a361658a26e50af6466

**Comment by WagnerThomas** [comment]
Fix working!
