### ISSUE TITLE
Back Button on detail bill crashing app

### ISSUE THREAD

**Issue by WagnerThomas** [mobileappdevhm20/team-project-team_6#52]
If you're trying to go back from an detail bill the app crashes (with device back button or the back arrow in the top left corner)

```java.lang.IllegalArgumentException: LayoutManager androidx.recyclerview.widget.LinearLayoutManager@b832d29 is already attached to a RecyclerView: androidx.recyclerview.widget.RecyclerView{552e8ae VFED.V... ......ID 0,0-1080,1700 #7f0900f7 app:id/recyclerView}, adapter:com.easybill.ui.archive.ArchiveListAdapter@bc6464f, layout:androidx.recyclerview.widget.LinearLayoutManager@b832d29, context:com.easybill.MainActivity@563f5c9```

**Comment by jjxxs** [comment]
Fixed in https://github.com/mobileappdevhm20/team-project-team_6/commit/2bbdd1ee18453ae6e59b7a361658a26e50af6466

**Comment by WagnerThomas** [comment]
Working!
