### ISSUE TITLE
Total of a bill is sometimes not shown

### ISSUE THREAD

**Issue by WagnerThomas** [mobileappdevhm20/team-project-team_6#54]
If there are to many items in a bill, the total is not shown.

![image](https://user-images.githubusercontent.com/43779014/85270931-5a2b0500-b47a-11ea-9417-3c5c55b021c3.png)
![image](https://user-images.githubusercontent.com/43779014/85270975-6b741180-b47a-11ea-9e2d-c086caf937b3.png)

**Comment by jjxxs** [comment]
Fixed in https://github.com/mobileappdevhm20/team-project-team_6/commit/2bbdd1ee18453ae6e59b7a361658a26e50af6466

**Comment by WagnerThomas** [comment]
Working!
