### ISSUE TITLE
App crashing in statistics fragment

### ISSUE THREAD

**Issue by WagnerThomas** [mobileappdevhm20/team-project-team_6#55]
If there is no given bill in a timeframe (zooming in to much) the app crashes.

```java.util.NoSuchElementException: List is empty.```

**Comment by jjxxs** [comment]
Can't reproduce, maybe fixed with https://github.com/mobileappdevhm20/team-project-team_6/commit/2bbdd1ee18453ae6e59b7a361658a26e50af6466

Please try again.

**Comment by WagnerThomas** [comment]
Working! There is a least one bill shown in the timeframe no matter how far you zoom in.
