### ISSUE TITLE
Deleting a bill crashes the app

### ISSUE THREAD

**Issue by WagnerThomas** [mobileappdevhm20/team-project-team_6#56]
Trying to delete a bill will crash the app.
Probably the same error as #52 

java.lang.IllegalArgumentException: LayoutManager androidx.recyclerview.widget.LinearLayoutManager@3e7da8b is already attached to a RecyclerView: androidx.recyclerview.widget.RecyclerView{d09768 VFED.V... ........ 0,0-1080,1700 #7f0900f7 app:id/recyclerView}, adapter:com.easybill.ui.archive.ArchiveListAdapter@9625781, layout:androidx.recyclerview.widget.LinearLayoutManager@3e7da8b, context:com.easybill.MainActivity@563f5c9
        at androidx.recyclerview.widget.RecyclerView.setLayoutManager(RecyclerView.java:1345)

**Comment by jjxxs** [comment]
Probably fixed in https://github.com/mobileappdevhm20/team-project-team_6/commit/2bbdd1ee18453ae6e59b7a361658a26e50af6466

Can you verify?

**Comment by WagnerThomas** [comment]
Fixed and working flawlessly!
