### ISSUE TITLE
Apply ordering to archived bills

### ISSUE THREAD

**Issue by jjxxs** [mobileappdevhm20/team-project-team_6#6]
It should be possible to order the archived bills by certain values (e.g. time, sum) in ascending or descending directions.

- [x] In the "archive"-View it's possible to order the bills.

**Comment by WagnerThomas** [comment]
Logic is kinda implemented for filtering based on sum.

**Comment by WagnerThomas** [comment]
logic for filtering bills is kinda implemented. 
Problem: database is still quite buggy (bills are sometimes not shown)
This should be fixed based on @jjxxs UI revamp and great work!
I'll start implementing my code in the new UI when its ready to be worked on.
Currently still trying more filter options on my branch
