### ISSUE TITLE
Setup Database for Bills

### ISSUE THREAD

**Issue by salman2893** [mobileappdevhm20/team-project-team_6#8]
Setup a database to store, delete and fetch bill.

- [x] Bills can be stored
- [x] Bills can be fetched from the database
- [x] Bills can be deleted
- [x] The database can be accessed through a Repository

**Comment by ReneNeu** [comment]
Successful review after the Sprint meeting on 29.05.2020

**Comment by WagnerThomas** [comment]
To insert data into the database use the bill.kt class (its not the class which is inserted into the database but fits more the needs of a representative class for a bill)
Based on this bill.kt, the database inserts the according values into the database.

Insert returns the ID of the inserted object.

**Comment by WagnerThomas** [comment]
The getBill methods returns not a bill, but the billDatabase class. 
Accordingly getItem returns the itemDatabaseclass.

**Comment by WagnerThomas** [comment]
To use the database, just create an instance of the billDataBase
